spring.application.name=auth-service
server:
port: 8081
tomcat=
threads=
max= 200
min-spare= 20
accept-count= 100


logging=
level=
root= INFO
com.edna.dxl= DEBUG
pattern=
console= "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId}] %-5level %logger - %msg%n"


