spring.application.name=dxl-service
server=
port= 8080
#thread & tomcat tuning
tomcat=
threads=
max= 200
min-spare= 20
accept-count= 100
#circuit breaker Config
resilience4j=
circuitbreaker=
instances=
billingService=
failureRateThreshold= 50
minimumNumberOfCalls= 5
waitDurationInOpenState= 10s
slidingWindowSize= 10

#timeouts
feign=
client=
config=
default=
connectTimeout= 3000
readTimeout= 5000

#centralised logging
logging=
level=
root= INFO
com.edna.dxl= DEBUG
pattern=
console= "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId}] %-5level %logger - %msg%n"

#enable tracing
management=
tracing=
sampling=
probability= 1.0
