spring.application.name=billing-service
server=
port= 8082
tomcat=
threads=
max= 200
min-spare= 20
accept-count= 100

#centalised logging
logging=
level=
root= INFO
com.edna.dxl= DEBUG
pattern=
console= "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId}] %-5level %logger - %msg%n"


spring=
datasource=
url= jdbc:postgresql://postgres:5432/billingdb
username= billing
password= billing
jpa=
hibernate=
ddl-auto= update
show-sql= false
#postgres
services=
postgres=
image= postgres:15
environment=
POSTGRES_DB= billingdb
POSTGRES_USER= billing
POSTGRES_PASSWORD= billing
ports=
-="5432:5432"

billing-service=
depends_on=postgres



